//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://passport.shu.edu.cn/", ConfigurationName="ServiceReference1.SendMsgSoap")]
    public interface SendMsgSoap {
        
        // CODEGEN: 消息 SendMsgChannel1Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.shu.edu.cn/SendMsgChannel1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XF.ServiceReference1.SendMsgChannel1Response SendMsgChannel1(XF.ServiceReference1.SendMsgChannel1Request request);
        
        // CODEGEN: 消息 SendMsgChannel2Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://passport.shu.edu.cn/SendMsgChannel2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        XF.ServiceReference1.SendMsgChannel2Response SendMsgChannel2(XF.ServiceReference1.SendMsgChannel2Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://passport.shu.edu.cn/")]
    public partial class ShuSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nMsgField;
        
        private string userIDField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NMsg {
            get {
                return this.nMsgField;
            }
            set {
                this.nMsgField = value;
                this.RaisePropertyChanged("NMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsgChannel1", WrapperNamespace="http://passport.shu.edu.cn/", IsWrapped=true)]
    public partial class SendMsgChannel1Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://passport.shu.edu.cn/")]
        public XF.ServiceReference1.ShuSoapHeader ShuSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://passport.shu.edu.cn/", Order=0)]
        public string mobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://passport.shu.edu.cn/", Order=1)]
        public string contents;
        
        public SendMsgChannel1Request() {
        }
        
        public SendMsgChannel1Request(XF.ServiceReference1.ShuSoapHeader ShuSoapHeader, string mobiles, string contents) {
            this.ShuSoapHeader = ShuSoapHeader;
            this.mobiles = mobiles;
            this.contents = contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsgChannel1Response", WrapperNamespace="http://passport.shu.edu.cn/", IsWrapped=true)]
    public partial class SendMsgChannel1Response {
        
        public SendMsgChannel1Response() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsgChannel2", WrapperNamespace="http://passport.shu.edu.cn/", IsWrapped=true)]
    public partial class SendMsgChannel2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://passport.shu.edu.cn/")]
        public XF.ServiceReference1.ShuSoapHeader ShuSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://passport.shu.edu.cn/", Order=0)]
        public string mobiles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://passport.shu.edu.cn/", Order=1)]
        public string contents;
        
        public SendMsgChannel2Request() {
        }
        
        public SendMsgChannel2Request(XF.ServiceReference1.ShuSoapHeader ShuSoapHeader, string mobiles, string contents) {
            this.ShuSoapHeader = ShuSoapHeader;
            this.mobiles = mobiles;
            this.contents = contents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMsgChannel2Response", WrapperNamespace="http://passport.shu.edu.cn/", IsWrapped=true)]
    public partial class SendMsgChannel2Response {
        
        public SendMsgChannel2Response() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendMsgSoapChannel : XF.ServiceReference1.SendMsgSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendMsgSoapClient : System.ServiceModel.ClientBase<XF.ServiceReference1.SendMsgSoap>, XF.ServiceReference1.SendMsgSoap {
        
        public SendMsgSoapClient() {
        }
        
        public SendMsgSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendMsgSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMsgSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendMsgSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference1.SendMsgChannel1Response XF.ServiceReference1.SendMsgSoap.SendMsgChannel1(XF.ServiceReference1.SendMsgChannel1Request request) {
            return base.Channel.SendMsgChannel1(request);
        }
        
        public void SendMsgChannel1(XF.ServiceReference1.ShuSoapHeader ShuSoapHeader, string mobiles, string contents) {
            XF.ServiceReference1.SendMsgChannel1Request inValue = new XF.ServiceReference1.SendMsgChannel1Request();
            inValue.ShuSoapHeader = ShuSoapHeader;
            inValue.mobiles = mobiles;
            inValue.contents = contents;
            XF.ServiceReference1.SendMsgChannel1Response retVal = ((XF.ServiceReference1.SendMsgSoap)(this)).SendMsgChannel1(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference1.SendMsgChannel2Response XF.ServiceReference1.SendMsgSoap.SendMsgChannel2(XF.ServiceReference1.SendMsgChannel2Request request) {
            return base.Channel.SendMsgChannel2(request);
        }
        
        public void SendMsgChannel2(XF.ServiceReference1.ShuSoapHeader ShuSoapHeader, string mobiles, string contents) {
            XF.ServiceReference1.SendMsgChannel2Request inValue = new XF.ServiceReference1.SendMsgChannel2Request();
            inValue.ShuSoapHeader = ShuSoapHeader;
            inValue.mobiles = mobiles;
            inValue.contents = contents;
            XF.ServiceReference1.SendMsgChannel2Response retVal = ((XF.ServiceReference1.SendMsgSoap)(this)).SendMsgChannel2(inValue);
        }
    }
}
