//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.MsgModemWebServerSoap")]
    public interface MsgModemWebServerSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        XF.ServiceReference3.HelloWorldResponse HelloWorld(XF.ServiceReference3.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 MsgTo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageEachMinute", ReplyAction="*")]
        XF.ServiceReference3.SendMessageEachMinuteResponse SendMessageEachMinute(XF.ServiceReference3.SendMessageEachMinuteRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 MsgTo 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        XF.ServiceReference3.SendMessageResponse SendMessage(XF.ServiceReference3.SendMessageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetComNumResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetComNum", ReplyAction="*")]
        XF.ServiceReference3.GetComNumResponse GetComNum(XF.ServiceReference3.GetComNumRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(XF.ServiceReference3.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(XF.ServiceReference3.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageEachMinuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageEachMinute", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.SendMessageEachMinuteRequestBody Body;
        
        public SendMessageEachMinuteRequest() {
        }
        
        public SendMessageEachMinuteRequest(XF.ServiceReference3.SendMessageEachMinuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageEachMinuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgContent;
        
        public SendMessageEachMinuteRequestBody() {
        }
        
        public SendMessageEachMinuteRequestBody(string MsgTo, string MsgContent) {
            this.MsgTo = MsgTo;
            this.MsgContent = MsgContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageEachMinuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageEachMinuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.SendMessageEachMinuteResponseBody Body;
        
        public SendMessageEachMinuteResponse() {
        }
        
        public SendMessageEachMinuteResponse(XF.ServiceReference3.SendMessageEachMinuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageEachMinuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageEachMinuteResult;
        
        public SendMessageEachMinuteResponseBody() {
        }
        
        public SendMessageEachMinuteResponseBody(string SendMessageEachMinuteResult) {
            this.SendMessageEachMinuteResult = SendMessageEachMinuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(XF.ServiceReference3.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MsgTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgContent;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string MsgTo, string MsgContent) {
            this.MsgTo = MsgTo;
            this.MsgContent = MsgContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(XF.ServiceReference3.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComNumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComNum", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.GetComNumRequestBody Body;
        
        public GetComNumRequest() {
        }
        
        public GetComNumRequest(XF.ServiceReference3.GetComNumRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetComNumRequestBody {
        
        public GetComNumRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComNumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComNumResponse", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference3.GetComNumResponseBody Body;
        
        public GetComNumResponse() {
        }
        
        public GetComNumResponse(XF.ServiceReference3.GetComNumResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetComNumResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetComNumResult;
        
        public GetComNumResponseBody() {
        }
        
        public GetComNumResponseBody(string GetComNumResult) {
            this.GetComNumResult = GetComNumResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MsgModemWebServerSoapChannel : XF.ServiceReference3.MsgModemWebServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MsgModemWebServerSoapClient : System.ServiceModel.ClientBase<XF.ServiceReference3.MsgModemWebServerSoap>, XF.ServiceReference3.MsgModemWebServerSoap {
        
        public MsgModemWebServerSoapClient() {
        }
        
        public MsgModemWebServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MsgModemWebServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgModemWebServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MsgModemWebServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference3.HelloWorldResponse XF.ServiceReference3.MsgModemWebServerSoap.HelloWorld(XF.ServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            XF.ServiceReference3.HelloWorldRequest inValue = new XF.ServiceReference3.HelloWorldRequest();
            inValue.Body = new XF.ServiceReference3.HelloWorldRequestBody();
            XF.ServiceReference3.HelloWorldResponse retVal = ((XF.ServiceReference3.MsgModemWebServerSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference3.SendMessageEachMinuteResponse XF.ServiceReference3.MsgModemWebServerSoap.SendMessageEachMinute(XF.ServiceReference3.SendMessageEachMinuteRequest request) {
            return base.Channel.SendMessageEachMinute(request);
        }
        
        public string SendMessageEachMinute(string MsgTo, string MsgContent) {
            XF.ServiceReference3.SendMessageEachMinuteRequest inValue = new XF.ServiceReference3.SendMessageEachMinuteRequest();
            inValue.Body = new XF.ServiceReference3.SendMessageEachMinuteRequestBody();
            inValue.Body.MsgTo = MsgTo;
            inValue.Body.MsgContent = MsgContent;
            XF.ServiceReference3.SendMessageEachMinuteResponse retVal = ((XF.ServiceReference3.MsgModemWebServerSoap)(this)).SendMessageEachMinute(inValue);
            return retVal.Body.SendMessageEachMinuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference3.SendMessageResponse XF.ServiceReference3.MsgModemWebServerSoap.SendMessage(XF.ServiceReference3.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(string MsgTo, string MsgContent) {
            XF.ServiceReference3.SendMessageRequest inValue = new XF.ServiceReference3.SendMessageRequest();
            inValue.Body = new XF.ServiceReference3.SendMessageRequestBody();
            inValue.Body.MsgTo = MsgTo;
            inValue.Body.MsgContent = MsgContent;
            XF.ServiceReference3.SendMessageResponse retVal = ((XF.ServiceReference3.MsgModemWebServerSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference3.GetComNumResponse XF.ServiceReference3.MsgModemWebServerSoap.GetComNum(XF.ServiceReference3.GetComNumRequest request) {
            return base.Channel.GetComNum(request);
        }
        
        public string GetComNum() {
            XF.ServiceReference3.GetComNumRequest inValue = new XF.ServiceReference3.GetComNumRequest();
            inValue.Body = new XF.ServiceReference3.GetComNumRequestBody();
            XF.ServiceReference3.GetComNumResponse retVal = ((XF.ServiceReference3.MsgModemWebServerSoap)(this)).GetComNum(inValue);
            return retVal.Body.GetComNumResult;
        }
    }
}
