//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XF.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.MessageSendSoap")]
    public interface MessageSendSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Msg 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JWSend", ReplyAction="*")]
        XF.ServiceReference2.JWSendResponse JWSend(XF.ServiceReference2.JWSendRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JWSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JWSend", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference2.JWSendRequestBody Body;
        
        public JWSendRequest() {
        }
        
        public JWSendRequest(XF.ServiceReference2.JWSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JWSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Msg;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string JsNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string useraccount;
        
        public JWSendRequestBody() {
        }
        
        public JWSendRequestBody(string Msg, string JsNo, string useraccount) {
            this.Msg = Msg;
            this.JsNo = JsNo;
            this.useraccount = useraccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JWSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JWSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public XF.ServiceReference2.JWSendResponseBody Body;
        
        public JWSendResponse() {
        }
        
        public JWSendResponse(XF.ServiceReference2.JWSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JWSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JWSendResult;
        
        public JWSendResponseBody() {
        }
        
        public JWSendResponseBody(string JWSendResult) {
            this.JWSendResult = JWSendResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageSendSoapChannel : XF.ServiceReference2.MessageSendSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageSendSoapClient : System.ServiceModel.ClientBase<XF.ServiceReference2.MessageSendSoap>, XF.ServiceReference2.MessageSendSoap {
        
        public MessageSendSoapClient() {
        }
        
        public MessageSendSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageSendSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageSendSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageSendSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XF.ServiceReference2.JWSendResponse XF.ServiceReference2.MessageSendSoap.JWSend(XF.ServiceReference2.JWSendRequest request) {
            return base.Channel.JWSend(request);
        }
        
        public string JWSend(string Msg, string JsNo, string useraccount) {
            XF.ServiceReference2.JWSendRequest inValue = new XF.ServiceReference2.JWSendRequest();
            inValue.Body = new XF.ServiceReference2.JWSendRequestBody();
            inValue.Body.Msg = Msg;
            inValue.Body.JsNo = JsNo;
            inValue.Body.useraccount = useraccount;
            XF.ServiceReference2.JWSendResponse retVal = ((XF.ServiceReference2.MessageSendSoap)(this)).JWSend(inValue);
            return retVal.Body.JWSendResult;
        }
    }
}
